version: '3.8'

services:
  movie-app:
    build: .
    image: ghcr.io/sjnhnp/sjnhnp/movie:latest
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      # 在这里设置您的网站访问密码和设置密码
      - PASSWORD=your-secret-password
      - SETTINGS_PASSWORD=your-settings-password
    restart: unless-stopped